# Generated by Django 5.1.6 on 2025-03-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_film_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
